### ISSUE TITLE
[Attention] Website Issues

### ISSUE THREAD

**Issue by ArchiveBase** [cloudify-cosmo/docs.getcloudify.org#1059]
Hello,
i see this's a good project however seems like most're not care much.

--------------------------------

\# Docs https gone: https://docs.cloudify.co/4.6/
![image](https://user-images.githubusercontent.com/46082456/56434310-43c96c80-62fe-11e9-8356-e644c45aae73.png)
https://letsencrypt.org/

-----------------------------------

\# Website load too slow even atleast not load completely (without enable adblock)
\# Why there too much thirdparty remote services for homepage? [adblock blocks around 12 remoteurls]
https://cloudify.co

![image](https://user-images.githubusercontent.com/46082456/56434425-c520ff00-62fe-11e9-9a0c-276fd78e6aa4.png)

-----------------------------------------

dont tell me refresh page or clear cache ;)

**Comment by EarthmanT** [comment]
Hello, thanks for pointing this out. Seems like the SSL cert lapsed. Should be fixed now. Please try again.
