### ISSUE TITLE
Building from master fails

### ISSUE THREAD

**Issue by 01000101** [cloudify-cosmo/docs.getcloudify.org#1313]
**Describe the bug**
Using Hugo to build from master fails with 

```
Error: Error building site: "docs.getcloudify.org\content\_footer.md:1:1": plain HTML documents not supported
```

This happens both in Windows 10 and Ubuntu 20.04. 

**Hugo Version**
```
PS C:\Users\Cereal Killer\Desktop\Dev\cloudify\docs.getcloudify.org> hugo version
Hugo Static Site Generator v0.71.1-A301F6B2 windows/amd64 BuildDate: 2020-05-25T09:12:07Z
```
```
cerealkiller@thegibson:/mnt/hgfs/Dev/cloudify/docs.getcloudify.org$ hugo version
Hugo Static Site Generator v0.68.3/extended linux/amd64 BuildDate: 2020-03-25T06:15:45Z
```

**To Reproduce**
1. Go to the repo root directory
2. Run "hugo server"

**Expected behavior**
The docs are built and served

**Additional context**
I was able to work around this by editing _footer.md and placing the following snippet at the top of the file, saving, and retrying. 
```
---
---
```

This is likely due to recent changes outlined in this ticket - https://github.com/gohugoio/hugo/issues/7296

**Comment by alexmolev** [comment]
Fixed
