### ISSUE TITLE
missing how to install Cloudify on Ubuntu (through https://pypi.python.org/)

### ISSUE THREAD

**Issue by liormizr** [cloudify-cosmo/docs.getcloudify.org#142]
Hi guys,

In: http://getcloudify.org/downloads/get_cloudify.html

We don't have instructions how to install Cloudify through https://pypi.python.org/

This is relevant for users with linux distributions that aren't Centos 6.5 and 7 or RHEL 7

**Comment by bmansheim** [comment]
No longer relevant
