### ISSUE TITLE
wrong link in intro/cloudify-manager/

### ISSUE THREAD

**Issue by liormizr** [cloudify-cosmo/docs.getcloudify.org#144]
in page: http://docs.getcloudify.org/3.3.1/intro/cloudify-manager/

we have a link to:
http://docs.getcloudify.org/3.3.1/intro/cloudify-manager/No%20page%20found%20with%20path%20or%20logical%20name

(that give 404 - bad url...)

**Comment by bmansheim** [comment]
No longer relevant
