### ISSUE TITLE
Bad link in Blueprints/intrinsic functions

### ISSUE THREAD

**Issue by Ilanad** [cloudify-cosmo/docs.getcloudify.org#386]
in page: http://docs.getcloudify.org/4.0.0/blueprints/spec-intrinsic-functions/

Secrets is going to a 404 link. Not sure if this is supposed to go to the secret store section or the CLI/secrets section. 

@chanagershom @rtpro

**Comment by chanagershom** [comment]
Thanks. I will take a look (and fix it) tomorrow.

**Comment by bmansheim** [comment]
No longer relevant
