### ISSUE TITLE
Uploading a Blueprint using the Command Line, Error

### ISSUE THREAD

**Issue by leejshades** [cloudify-cosmo/docs.getcloudify.org#861]
can u tell me how to solve it?
`[root@cloudify cloudify-nodecellar-example]# cfy blueprints upload -b nodecellar -n openstack-blueprint.yaml  /root/cloudify-nodecellar-example/
You must provide either a path to a local file, a remote URL or a GitHub `organization/repository[:tag/branch]``

**Comment by bmansheim** [comment]
Hi. Thank you for contacting us.
From what I see in the documentation, the path must be to a specific blueprint archive, for example: /root/cloudify-nodecellar-example.zip
The best way to get help is from our support channels that are listed at https://cloudify.co/support including our mailing list and our slack channel: https://cloudify.co/slack/
Hope that helps!
